# Generated by Django 5.0.3 on 2024-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_no",
            field=models.IntegerField(null=True),
        ),
    ]
