# Generated by Django 5.0.3 on 2024-03-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_created_at_member_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="created_at",
            field=models.DateField(null=True),
        ),
    ]
